import test from 'node:test';
import assert from 'node:assert/strict';
import { createCommunityListingFixture, owner, reader, listingIds as ids } from './fixtures/community-listing.mjs';

const setup = createCommunityListingFixture(test);
const publishedPath = params => `topics?${new URLSearchParams({ sort: 'published', ...params })}`;
async function newsFixture(t) {
  const fixture = await setup(t);
  fixture.store.boards.create({ name: 'AI资讯', description: '记录 AI 与智能体的真实产品发布和行业信息。', icon: 'bot' }, owner);
  const summary = await fixture.list('summary');
  const source = summary.boardCatalog.items.find(board => board.zh === 'AI资讯');
  assert.ok(source, 'the source comes from the real catalog returned by the existing summary route');
  assert.match(source.id, /^board-[0-9a-f]+$/, 'the source ID is generated by the real board creation flow');
  return { ...fixture, source, news: (title, days = 0, options = {}) => fixture.topic(title, days, { board: source.id, ...options }) };
}

test('published reads the real news board and sorts its entire pool by publication time despite more than twenty old pinned posts', async t => {
  const f = await newsFixture(t), oldPins = [];
  for (let i = 0; i < 25; i++) oldPins.push(f.news(`较早置顶资讯 ${i}`, 100 + i, { pin: true }).id);
  const featured = f.news('早期精华资讯不应冒充最新', 40);
  f.store.setFeatured(featured.id, true);
  f.store.addReply({ topicId: featured.id, author: reader('author'), body: '这是今天的新回复，不改变资讯的发布时间。', now: f.ago(0) });
  const newItems = Array.from({ length: 8 }, (_, index) => f.news(`真实最新资讯 ${index}`, index / 1000));
  const legacy = await f.list(`topics?${new URLSearchParams({ board: f.source.id, sort: 'newest' })}`);
  assert.equal(legacy.pageSize, 20);
  assert.ok(legacy.items.every(item => oldPins.includes(item.id)), 'the legacy newest route really promotes old pins ahead of the eight newest posts');
  const actual = await f.list(publishedPath({ board: f.source.id, page: '1' }));
  assert.equal(actual.page, 1);
  assert.equal(actual.pageSize, 6);
  assert.equal(actual.total, 34);
  assert.deepEqual(ids(actual), newItems.slice(0, 6).map(item => item.id), 'chronological sorting occurs before six-item server paging');
  assert.deepEqual(actual.items.map(item => item.createdAt), newItems.slice(0, 6).map((_, index) => f.ago(index / 1000)), 'the existing DTO retains exact ISO publication timestamps for Beijing-time presentation');
  assert.ok(actual.items.every(item => item.board === f.source.id));
});

test('published ignores an active paid recommendation while legacy newest, curated and other API contracts remain intact', async t => {
  const f = await setup(t);
  const pinned = f.topic('较早的站长置顶资源', 100, { board: 'tools', pin: true });
  const paid = f.topic('较早的付费推荐资源', 80, { board: 'tools' });
  const featured = f.topic('较早的精华资源', 60, { board: 'tools' });
  f.store.setFeatured(featured.id, true);
  f.store.ledger.credit(owner, 400, 'test', null, f.ago(0));
  assert.equal(f.store.economy.paidPin(paid.id, owner).card, false);
  const newest = f.topic('真正最近发布的资源', 0, { board: 'tools' });
  const legacy = await f.list('topics?board=tools&sort=newest');
  assert.deepEqual(ids(legacy), [pinned.id, paid.id, newest.id, featured.id]);
  assert.equal(legacy.items.find(item => item.id === paid.id).paidPin, true);
  const actual = await f.list(publishedPath({ board: 'tools' }));
  assert.deepEqual(ids(actual), [newest.id, featured.id, paid.id, pinned.id]);
  assert.equal(actual.pageSize, 6);
  assert.equal((await f.list('topics?board=tools&sort=curated')).pageSize, 6);
  for (const sort of ['active', 'newest', 'hot', 'featured', 'following'])
    assert.equal((await f.list(`topics?board=tools&sort=${sort}`)).pageSize, 20, `existing ${sort} page size remains unchanged`);
  assert.equal((await f.list('topics?board=tools')).pageSize, 20, 'the existing API default does not become published');
  assert.equal((await f.get('topics?sort=unknown')).status, 400);
});

test('published pages one chronological board without missing or duplicating static entries', async t => {
  const f = await newsFixture(t), inserted = [];
  for (let i = 17; i >= 1; i--) inserted.push(f.news(`按时间分页的资讯 ${i}`, i).id);
  const expected = [...inserted].reverse(), all = [];
  for (let page = 1; page <= 3; page++) {
    const listing = await f.list(publishedPath({ board: f.source.id, page: String(page) }));
    assert.equal(listing.page, page);
    assert.equal(listing.pageSize, 6);
    assert.equal(listing.total, expected.length);
    assert.deepEqual(ids(listing), expected.slice((page - 1) * 6, page * 6));
    all.push(...ids(listing));
  }
  assert.deepEqual(all, expected);
  assert.equal(new Set(all).size, expected.length);
  assert.deepEqual((await f.list(publishedPath({ board: f.source.id, page: '4' }))).items, []);
});

test('published filters private titles and totals before paging and honors VIP expiry on the next read', async t => {
  const f = await newsFixture(t), publicIds = [], privateIds = [];
  for (let i = 0; i < 8; i++) publicIds.push(f.news(`公开资讯 ${i}`, 10 + i).id);
  for (let i = 0; i < 8; i++) privateIds.push(f.topic(`NEWS-VIP-PRIVATE-${i}`, i / 1000, { board: 'vip' }).id);
  const ordinary = await f.list(publishedPath({}));
  assert.equal(ordinary.total, publicIds.length);
  assert.deepEqual(ids(ordinary), publicIds.slice(0, 6));
  assert.equal(JSON.stringify(ordinary).includes('NEWS-VIP-PRIVATE'), false);
  assert.equal((await f.get(publishedPath({ board: 'vip' }))).status, 404);
  const member = await f.list(publishedPath({}), 'vip');
  assert.equal(member.total, publicIds.length + privateIds.length);
  assert.deepEqual(ids(member), privateIds.slice(0, 6));
  f.accounts.get('vip').vip = false;
  const expired = await f.list(publishedPath({}), 'vip');
  assert.equal(expired.total, publicIds.length);
  assert.deepEqual(ids(expired), publicIds.slice(0, 6));
  assert.equal(JSON.stringify(expired).includes('NEWS-VIP-PRIVATE'), false);
});

test('published rechecks moderator authorization during person lookup before returning private newest entries', async t => {
  const f = await newsFixture(t), publicIds = [];
  f.store.staff.appoint(owner, reader('mod'), { role: 'moderator', boards: [f.source.id, 'vip'], permissions: ['content.inspect'], delegable: [] });
  for (let i = 0; i < 8; i++) publicIds.push(f.news(`降权后可见资讯 ${i}`, 10 + i).id);
  for (let i = 0; i < 8; i++) f.topic(`NEWS-REVOKED-PRIVATE-${i}`, i / 1000, { board: 'vip' });
  let revoked = false;
  f.onPeople(authors => {
    if (!revoked && authors.some(author => author.kind === 'owner')) {
      revoked = true;
      f.store.staff.revoke(owner, reader('mod'));
    }
  });
  const listing = await f.list(publishedPath({}), 'mod');
  assert.equal(revoked, true);
  assert.equal(listing.total, publicIds.length);
  assert.deepEqual(ids(listing), publicIds.slice(0, 6));
  assert.equal(JSON.stringify(listing).includes('NEWS-REVOKED-PRIVATE'), false);
});

test('published respects real board, tag, search and author scopes and excludes pending, hidden and deleted news', async t => {
  const f = await newsFixture(t);
  const pending = f.news('未通过审核的资讯', 0, { pending: '需要审核' });
  const hidden = f.news('已被隐藏的资讯');
  const deleted = f.news('已被删除的资讯');
  for (const item of [pending, hidden, deleted]) f.store.setFeatured(item.id, true);
  f.store.hide({ kind: 'topic', id: hidden.id }, '测试隐藏');
  f.store.deleteTopic(deleted.id);
  const empty = await f.list(publishedPath({ board: f.source.id }));
  assert.equal(empty.total, 0);
  assert.deepEqual(empty.items, [], 'an empty news board stays empty instead of borrowing another source');
  const older = f.news('命中较早资讯', 10, { tags: ['提示词'], author: reader('author') });
  const newer = f.news('命中较新资讯', 1, { tags: ['提示词'] });
  f.news('不匹配的资讯', 0, { tags: ['工作流'] });
  f.topic('命中其他板块不能混入', 0, { tags: ['提示词'] });
  assert.deepEqual(ids(await f.list(publishedPath({ board: f.source.id, tag: '提示词', q: '命中' }))), [newer.id, older.id]);
  assert.deepEqual(ids(await f.list(publishedPath({ board: f.source.id, author: '10004' }))), [older.id]);
  assert.equal((await f.get(publishedPath({ board: 'missing-news-board' }))).status, 404, 'an invalid source has no fallback to all topics');
  assert.equal((await f.get(publishedPath({ tag: '未知标签' }))).status, 404);
  assert.equal((await f.get(publishedPath({ board: f.source.id }), '')).status, 401);
});
