import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { getPayload, createLocalReq, logoutOperation } from 'payload';
import { makePayloadConfig } from '../server/payload/config.ts';
import { loginEventsSchema } from '../server/payload/reader-migration.ts';
import { migratePayloadAuthSecurity, assertPayloadAuthSchemaReady } from '../server/payload/auth-security-migration.ts';
import { legacyAuthFixture } from './fixtures/payload-auth-3-89.mjs';

test('explicitly migrated 3.89 accounts authenticate, upgrade hashes, reset locks/sessions and survive a push:false restart without changing UID/VIP/uploads', { timeout: 120000 }, async () => {
  const directory = await mkdtemp(resolve(tmpdir(), 'sansphase-auth-upgrade-integration-'));
  const secret = randomBytes(48).toString('hex'), sent = [];
  const emailAdapter = () => ({ name: 'isolated-upgrade-mail', defaultFromAddress: 'noreply@example.test', defaultFromName: 'Fixture', sendEmail: async mail => { sent.push(mail); } });
  let payload;
  const close = async () => { if (payload) { await payload.destroy(); await payload.db.client.close(); payload = undefined; } };
  try {
    payload = await getPayload({ config: makePayloadConfig({ directory, secret, push: true, emailAdapter }), key: `auth-schema-${directory}` });
    const modernColumns = {};
    const modern = new DatabaseSync(resolve(directory, 'content.db'), { readOnly: true });
    const shape = (db, table) => db.prepare(`PRAGMA table_xinfo(${table})`).all().map(({ cid: _cid, ...column }) => column).sort((a, b) => String(a.name).localeCompare(String(b.name)));
    for (const table of ['authors', 'readers']) modernColumns[table] = shape(modern, table);
    modern.close();
    const media = await payload.create({ collection: 'media', data: { title: '模拟上传', originalName: 'fixture.txt' }, file: { data: Buffer.from('immutable isolated media'), name: 'fixture.txt', mimetype: 'text/plain', size: 24 } });
    await payload.create({ collection: 'site_profile', data: { name: '模拟既有作者资料', signature: '迁移不得修改' } });
    await close();
    const db = new DatabaseSync(resolve(directory, 'content.db'));
    db.exec('PRAGMA foreign_keys=OFF; DROP TABLE authors_sessions; DROP TABLE readers_sessions; DROP TABLE authors; DROP TABLE readers;');
    for (const type of ['table', 'index', 'trigger']) for (const entry of legacyAuthFixture.schema.filter(row => row.type === type)) db.exec(entry.sql);
    for (const [table, rows] of Object.entries(legacyAuthFixture.accounts)) for (const row of rows) {
      const fields = Object.keys(row);
      db.prepare(`INSERT INTO ${table}(${fields.join(',')}) VALUES(${fields.map(() => '?').join(',')})`).run(...Object.values(row));
    }
    db.exec(loginEventsSchema);
    const beforeAuthor = db.prepare('SELECT * FROM authors').get(), beforeReader = db.prepare('SELECT * FROM readers').get();
    const beforeUID = db.prepare('SELECT * FROM reader_uids').all();
    const otherSchema = db.prepare("SELECT type,name,sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT IN ('authors','readers') ORDER BY type,name").all();
    db.close();
    const originalUpload = await readFile(resolve(directory, 'uploads', media.filename));
    await writeFile(resolve(directory, 'migration-complete.json'), JSON.stringify({ provider: 'payload' }));
    const migrated = await migratePayloadAuthSecurity(directory);
    assert.deepEqual(migrated.tables, ['authors', 'readers']);
    assertPayloadAuthSchemaReady(directory);
    const after = new DatabaseSync(resolve(directory, 'content.db'), { readOnly: true });
    for (const table of ['authors', 'readers']) assert.deepEqual(shape(after, table), modernColumns[table], 'actual fresh 3.90 schema and explicitly upgraded auth schema must match without push');
    assert.deepEqual(after.prepare("SELECT type,name,sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT IN ('authors','readers') ORDER BY type,name").all(), otherSchema);
    const { reset_password_requested_at: authorDate, ...author } = after.prepare('SELECT * FROM authors').get();
    const { reset_password_requested_at: readerDate, ...reader } = after.prepare('SELECT * FROM readers').get();
    assert.equal(authorDate, null); assert.equal(readerDate, null);
    assert.deepEqual(author, { ...beforeAuthor }); assert.deepEqual(reader, { ...beforeReader }); after.close();
    payload = await getPayload({ config: makePayloadConfig({ directory, secret, push: false, emailAdapter }), key: `auth-upgraded-${directory}` });
    const oldAuthor = legacyAuthFixture.accounts.authors[0], oldReader = legacyAuthFixture.accounts.readers[0];
    assert.equal((await payload.login({ collection: 'authors', data: { email: oldAuthor.email, password: legacyAuthFixture.password } })).user.id, oldAuthor.id);
    const oldSession = await payload.login({ collection: 'readers', data: { email: oldReader.email, password: legacyAuthFixture.password } });
    assert.equal(oldSession.user.id, oldReader.id);
    const upgraded = new DatabaseSync(resolve(directory, 'content.db'));
    assert.match(upgraded.prepare('SELECT hash FROM authors').get().hash, /^pbkdf2-sha256-v1:/);
    assert.match(upgraded.prepare('SELECT hash FROM readers').get().hash, /^pbkdf2-sha256-v1:/);
    assert.deepEqual(upgraded.prepare('SELECT * FROM reader_uids').all(), beforeUID);
    upgraded.prepare('UPDATE readers SET login_attempts=8,lock_until=? WHERE id=?').run(new Date(Date.now() + 600000).toISOString(), oldReader.id);
    upgraded.close();
    await assert.rejects(payload.login({ collection: 'readers', data: { email: oldReader.email, password: legacyAuthFixture.password } }), { status: 401 });
    const token = await payload.forgotPassword({ collection: 'readers', data: { email: oldReader.email } });
    assert.equal(typeof token, 'string'); assert.equal(sent.length, 1);
    await payload.forgotPassword({ collection: 'readers', data: { email: oldReader.email } });
    assert.equal(sent.length, 1, 'the real reset-request timestamp rate limit must not send duplicate mail');
    const resetPassword = 'isolated-reset-password-2026';
    const reset = await payload.resetPassword({ collection: 'readers', data: { token, password: resetPassword } });
    assert.equal((await payload.auth({ headers: new Headers({ Authorization: `JWT ${oldSession.token}` }) })).user, null);
    await logoutOperation({ allSessions: true, collection: payload.collections.readers, req: await createLocalReq({ user: reset.user }, payload) });
    assert.equal((await payload.auth({ headers: new Headers({ Authorization: `JWT ${reset.token}` }) })).user, null);
    const locked = new DatabaseSync(resolve(directory, 'content.db'), { readOnly: true });
    const resetRow = locked.prepare('SELECT login_attempts,lock_until,reset_password_requested_at FROM readers').get();
    assert.equal(resetRow.login_attempts, 0); assert.equal(resetRow.lock_until, null); assert.ok(resetRow.reset_password_requested_at); locked.close();
    const newPassword = 'isolated-new-reader-password-2026';
    const created = await payload.create({ collection: 'readers', disableVerificationEmail: true, data: { email: 'new-reader@example.test', password: newPassword, nickname: '新模拟读者', phone: '13900139000', _verified: true } });
    await close();
    payload = await getPayload({ config: makePayloadConfig({ directory, secret, push: false, emailAdapter }), key: `auth-restarted-${directory}` });
    assert.equal((await payload.login({ collection: 'readers', data: { email: oldReader.email, password: resetPassword } })).user.id, oldReader.id);
    assert.equal((await payload.login({ collection: 'readers', data: { email: created.email, password: newPassword } })).user.id, created.id);
    assert.equal((await payload.login({ collection: 'authors', data: { email: oldAuthor.email, password: legacyAuthFixture.password } })).user.id, oldAuthor.id);
    const final = new DatabaseSync(resolve(directory, 'content.db'), { readOnly: true });
    const persistent = final.prepare('SELECT nickname,phone,signature,avatar,vip_started_at,vip_until FROM readers WHERE id=?').get(oldReader.id);
    assert.deepEqual(persistent, Object.assign(Object.create(null), Object.fromEntries(Object.keys(persistent).map(key => [key, beforeReader[key]]))));
    assert.deepEqual(final.prepare('SELECT * FROM reader_uids WHERE reader_id=?').all(oldReader.id), beforeUID);
    assert.equal(final.prepare('PRAGMA integrity_check').get().integrity_check, 'ok');
    assert.deepEqual(final.prepare('PRAGMA foreign_key_check').all(), []); final.close();
    assert.deepEqual(await readFile(resolve(directory, 'uploads', media.filename)), originalUpload);
    assert.equal((await payload.find({ collection: 'site_profile' })).docs[0].name, '模拟既有作者资料');
  } finally { await close(); await rm(directory, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); }
});
