import busboy from 'busboy';
import {createWriteStream} from 'node:fs';
import {mkdir,mkdtemp,rm,statfs} from 'node:fs/promises';
import {resolve,basename,sep} from 'node:path';
import {pipeline} from 'node:stream/promises';

import {uploadLimits,uploadSizeLabel} from '../src/upload-policy.mjs';
export {uploadLimits};
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
// Busboy parses multipart incrementally. The temporary path is generated by us,
// never derived from an uploaded filename, and stays outside the public root.
export async function withStreamUpload(req,directory,consume,limits=uploadLimits) {
  const declared=Number(req.headers['content-length']);
  if(Number.isFinite(declared) && declared>limits.maxFileBytes+65536) throw fail(`文件超过 ${uploadSizeLabel(limits.maxFileBytes)} 上传上限。`,413);
  const root=resolve(directory,'incoming'); await mkdir(root,{recursive:true});
  const disk=await statfs(root);
  if(disk.bavail*disk.bsize < 2*(declared||limits.maxFileBytes)+512*1024**2) throw fail('服务器剩余空间不足，请清理文件或使用外部下载链接。',507);
  const temp=await mkdtemp(resolve(root,'upload-'));
  if(!temp.startsWith(root+sep)) throw fail('上传临时目录无效。');
  const tempFilePath=resolve(temp,'data');
  let write,uploaded,fault;
  const fields={};
  const abort=new AbortController();
  try {
    const parser=busboy({headers:req.headers,defParamCharset:'utf8',limits:{fileSize:limits.maxFileBytes+1,files:1,fields:3,fieldSize:1000,parts:5}});
    await new Promise((done,reject)=>{
      const onAbort=()=>{abort.abort();parser.destroy(fail('上传已中断。'));};
      req.once('aborted',onAbort);
      parser.on('field',(name,value)=>{fields[name]=value;});
      for(const event of ['filesLimit','fieldsLimit','partsLimit']) parser.on(event,()=>{fault=fail('一次只能上传一个文件。');});
      parser.on('file',(name,stream,info)=>{
        if(name!=='file' || !info.filename){fault=fail('请选择文件。');stream.resume();return;}
        uploaded={name:basename(info.filename.replaceAll('\\','/')),mimetype:info.mimeType,size:0,tempFilePath,data:Buffer.alloc(0)};
        const cap=info.mimeType.startsWith('image/') ? limits.maxImageBytes : info.mimeType.startsWith('audio/') ? limits.maxAudioBytes : limits.maxFileBytes;
        stream.on('data',chunk=>{uploaded.size+=chunk.length;if(uploaded.size>cap && !fault){fault=fail(`此类文件最多 ${uploadSizeLabel(cap)}。`,413);abort.abort();}});
        stream.on('limit',()=>{fault=fail('文件超过上传上限。',413);});
        write=pipeline(stream,createWriteStream(tempFilePath,{flags:'wx',mode:0o600}),{signal:abort.signal}).catch(error=>{fault ||= error;parser.destroy(fault);});
      });
      parser.once('error',error=>{req.unpipe(parser);req.resume();reject(fault||error);});
      parser.once('close',()=>{req.removeListener('aborted',onAbort);done();});
      req.pipe(parser);
    });
    await write;
    if(fault) throw fault;
    if(!uploaded || !uploaded.size) throw fail('请选择非空文件。');
    return await consume(uploaded,fields);
  } finally {
    abort.abort(); await write;
    await rm(temp,{recursive:true,force:true});
  }
}
