import { avatarHTML, nameLabelHTML } from './community.mjs';
import { communityLevels } from './community-rules.mjs';
import type { ShopCategory } from './community-rules.ts';
import type { Common, CommunityPerson } from './community.ts';
import type { CommunityManagedItem } from './community-pages.ts';

export function communityCategoryEditorHTML(categories: ShopCategory[], { t, esc }: Common) {
  return `<details class="community-category-manager" data-management-categories><summary>${t('商品分类', 'Product categories')}<span>${t('管理 / 新增', 'Manage / add')}</span></summary><div class="community-category-list" data-category-list>${categories.map(category => `<span>${esc(category.name)}</span>`).join('')}</div><form data-community-form="category" class="community-category-form" novalidate><div class="community-field"><label for="community-category-name">${t('新分类名称', 'New category')}</label><input id="community-category-name" name="name" maxlength="20" placeholder="${t('例如：星海系列', 'e.g. Star collection')}"></div><button type="submit" class="community-button">${t('添加分类', 'Add category')}</button><p class="community-form-status" role="status" aria-live="polite"></p></form></details>`;
}

export function communityShopEditorHTML(item: CommunityManagedItem | null, categories: ShopCategory[], common: Common) {
  const { t, esc, icons = {} } = common;
  const kind = item?.kind || 'goods';
  const cat = kind === 'frame' || kind === 'color' || kind === 'cover' ? 'look' : kind;
  const types = [['goods', t('实物周边', 'Physical goods')], ['digital', t('数字资源', 'Digital resource')], ['card', t('补签卡', 'Make-up card')], ['frame', t('头像框装备', 'Avatar frame')], ['color', t('昵称特效', 'Nickname effect')], ['cover', t('主页背景', 'Profile background')]];
  const locked = item?.canChangeKind === false;
  const effect = item?.effect || null;
  const field = (name: string, label: string, input: string) => `<div class="community-field"><label class="community-field-l" for="community-item-${name}">${label}</label>${input.replace('<INPUT', `<input id="community-item-${name}" name="${name}"`).replace('<TEXTAREA', `<textarea id="community-item-${name}" name="${name}"`).replace('<SELECT', `<select id="community-item-${name}" name="${name}" class="community-select"`)}</div>`;
  const sample: CommunityPerson = { name: t('無相', 'Preview'), uid: null, role: 'reader', frame: kind === 'frame' && item?.image ? `image:${item.image}` : null, nameEffect: kind === 'color' ? effect : null };
  return `<form class="community-panel community-item-form" data-community-form="item" data-id="${esc(item?.id || '')}" novalidate><div class="community-editor-heading"><h2>${item ? t(`编辑「${esc(item.name)}」`, `Edit ${esc(item.name)}`) : t('上架新物品', 'New product')}</h2><p class="community-muted">${t('先选物品类型，再设置分类和兑换条件。装扮兑换后可在已拥有中使用或更换。', 'Select a product type, category and redemption conditions. Redeemed looks can be applied or changed in Owned items.')}</p></div><input type="hidden" name="cat" value="${cat}">`
    + (locked ? `<input type="hidden" name="kind" value="${kind}"><p class="community-field-l">${t('物品类型：', 'Type: ')}${types.find(([value]) => value === kind)?.[1] || kind}</p><p class="community-muted">${t('已有兑换记录，不能改变购买者获得的物品用途。仍可更改分类分组或上下架；需要另一种用途时，请上架新物品。', 'Redemption history protects the item purpose. You can still change its collection and availability; create a new item for a different purpose.')}</p>` : `<fieldset class="community-inline-choices"><legend class="community-field-l">${t('物品类型', 'Product type')}</legend>${types.map(([value, label]) => `<label><input type="radio" name="kind" value="${value}"${kind === value ? ' checked' : ''}><span>${label}</span></label>`).join('')}</fieldset>`)
    + `<input type="hidden" name="ref" value="${esc(item?.kind === 'card' && item.ref ? item.ref : 'makeup')}"><label class="community-check"><input type="checkbox" name="active"${item?.active === false ? '' : ' checked'}><span>${t('上架中（取消勾选后保存即下架）', 'Available (uncheck and save to unlist)')}</span></label>`
    + `<div class="community-field-grid">${field('category', t('分类分组', 'Collection'), `<SELECT><option value="">${t('默认分组', 'Default collection')}</option>${categories.map(category => `<option value="${esc(category.id)}"${item?.category === category.id ? ' selected' : ''}>${esc(category.name)}</option>`).join('')}</select>`)}${field('name', t('名称', 'Name'), `<INPUT type="text" maxlength="30" required value="${esc(item?.name || '')}">`)}</div>`
    + `<div class="community-product-upload community-equipment-drop" data-item-media${kind === 'color' ? ' hidden' : ''}><div class="community-product-preview" data-item-image-preview>${item?.image ? `<img src="/api/community/images/${esc(item.image)}.webp" alt="${esc(item.name)}">` : `${icons.image || ''}<span>${t('拖入图片', 'Drop an image')}</span>`}</div><div><strong class="community-drop-title">${t('把桌面或文件夹里的图片直接拖到这里', 'Drag an image from your desktop or folder here')}</strong><p class="community-muted" id="community-item-media-help" data-item-media-help>${t('支持 JPG、PNG、WebP、GIF，最多 25MB / 120 帧。', 'JPG, PNG, WebP, GIF; up to 25MB / 120 frames.')}</p><label class="community-button is-small" for="community-item-image">${icons['image-plus'] || icons.image || ''}<span>${t('或选择图片', 'Or choose an image')}</span></label><input class="sr-only" id="community-item-image" type="file" accept="image/jpeg,image/png,image/webp,image/gif" data-community-item-upload aria-describedby="community-item-media-help"><input type="hidden" name="image" value="${esc(item?.image || '')}"><button type="button" class="community-button is-small" data-action="community-item-image-remove"${item?.image ? '' : ' hidden'}>${t('移除图片', 'Remove image')}</button><p class="community-upload-status" data-item-upload-status role="status" aria-live="polite"></p></div></div>`
    + `<div data-item-effect${kind !== 'color' ? ' hidden' : ''}><div class="community-effect-import community-equipment-drop"><div><strong class="community-drop-title">${t('把制作好的昵称特效文件拖到这里', 'Drop the finished nickname effect file here')}</strong><p class="community-muted" id="community-item-effect-help">${t('使用配套的 .json 效果文件，导入后预览；更换效果时拖入新的文件即可。', 'Import the matching .json effect file to preview it; drop a new file to replace the effect.')}</p><p class="community-upload-status" data-item-effect-status role="status" aria-live="polite"></p></div><label class="community-button is-small" for="community-item-effect-file">${icons['file-up'] || icons.upload || ''}<span>${t('或选择效果文件', 'Or choose an effect file')}</span></label><input class="sr-only" id="community-item-effect-file" type="file" accept=".json,application/json" data-community-effect-upload aria-describedby="community-item-effect-help"></div><input type="hidden" name="effectStyle" value="${effect?.style || ''}"><input type="hidden" name="effectStart" value="${effect?.colors[0] || ''}"><input type="hidden" name="effectEnd" value="${effect?.colors[1] || ''}"></div>`
    + `<div class="community-wear-preview" data-item-wear-preview${kind !== 'frame' && kind !== 'color' && kind !== 'cover' ? ' hidden' : ''}><div><span class="community-field-l">${t('使用效果预览', 'Appearance preview')}</span><p class="community-muted" data-item-wear-help></p></div><div data-item-wear-sample>${kind === 'cover' ? item?.image ? `<span class="community-cover-sample"><img src="/api/community/images/${esc(item.image)}.webp" alt="${esc(item.name)}"></span>` : '' : avatarHTML(sample, common, 'lg', false) + nameLabelHTML(sample, common)}</div></div>`
    + `<div class="community-field-grid community-editor-conditions">${field('price', t('价格（星尘）', 'Price (stardust)'), `<INPUT type="number" min="1" max="100000" step="1" required value="${item?.price ?? ''}">`)}<div data-item-stock>${field('stock', t('库存（实物必填，其余留空不限）', 'Stock (required for goods)'), `<INPUT type="number" min="0" max="100000" step="1" value="${item?.stock ?? ''}">`)}</div><div class="community-span-2">${field('description', t('说明', 'Description'), `<TEXTAREA rows="2" maxlength="200" required>${esc(item?.desc || '')}</textarea>`)}</div>`
    + field('limitPer', t('每人限兑', 'Per member'), `<SELECT>${[['', t('不限', 'No limit')], ['month', t('每月', 'Monthly')], ['year', t('每年', 'Yearly')], ['once', t('只能一次', 'Once')]].map(([value, label]) => `<option value="${value}"${item?.limit?.per === value ? ' selected' : ''}>${label}</option>`).join('')}</select>`)
    + field('limitN', t('每期次数', 'Times per period'), `<INPUT type="number" min="1" max="100" step="1" value="${item?.limit?.n ?? 1}">`)
    + field('minLevel', t('最低等级', 'Minimum level'), `<SELECT>${communityLevels.slice(0, 4).map(level => `<option value="${level.lv}"${(item?.minLevel || 0) === level.lv ? ' selected' : ''}>L${level.lv} ${t(level.name, level.en)}</option>`).join('')}</select>`)
    + field('minDays', t('注册天数', 'Account age (days)'), `<INPUT type="number" min="0" max="3650" step="1" value="${item?.minDays ?? 0}">`)
    + `<div class="community-span-2">${field('note', t('备注（比如包邮）', 'Note'), `<INPUT type="text" maxlength="60" value="${esc(item?.note || '')}">`)}</div><div class="community-span-2" data-item-delivery${kind !== 'digital' ? ' hidden' : ''}>${field('delivery', t('兑换后给出的内容（下载链接和提取码等）', 'Delivered content (link and code)'), `<TEXTAREA rows="3" maxlength="2000">${esc(item?.delivery || '')}</textarea>`)}</div></div><p class="community-form-status" role="status" aria-live="polite"></p><div class="community-form-actions"><button type="button" class="community-button" data-action="community-item-cancel">${t('取消', 'Cancel')}</button><button type="submit" class="community-button is-gold">${t('保存并应用', 'Save and apply')}</button></div></form>`;
}
